"use client";

import RulesAndLawLayout from "@/features/ui/rules-and-law-layout";

export default function PrivacyPolicyPage() {
  return (
    <RulesAndLawLayout>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni animi quis, ad odio ut corporis? Eius ad minima explicabo nisi vitae cupiditate asperiores molestias beatae dolore architecto veritatis reprehenderit ab iste voluptatibus, suscipit minus velit totam recusandae. Iure, maxime culpa distinctio aspernatur est sed, tempora accusantium dicta debitis deleniti quos. Necessitatibus vel sequi odio nulla ullam recusandae totam inventore, vero ea. Esse dolore molestias rem voluptatibus facere quaerat? Omnis, laboriosam adipisci! Alias veritatis quibusdam dolores laudantium corporis harum, fugit similique maiores a architecto officia reprehenderit omnis, optio ad magnam ducimus voluptatibus est qui exercitationem nemo culpa, fugiat nulla tenetur?</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis rerum ullam maiores mollitia sint consectetur nostrum sed odio nesciunt quos temporibus esse dolor molestiae quisquam deserunt, ex accusantium maxime aspernatur quia. Ipsum unde facere magnam repellendus corrupti est non mollitia, provident ipsam totam consectetur aperiam. Voluptatem obcaecati, esse ducimus soluta suscipit voluptas quo harum, temporibus nulla nesciunt debitis adipisci numquam? Nam cum dolorem, tenetur distinctio nemo magni animi atque velit quod iure voluptatibus, dolorum minus vitae.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ipsum quis in consectetur dolor quidem, aut mollitia numquam molestias. Nisi fugiat enim dicta eum minus odit natus perspiciatis quae! Assumenda culpa voluptatibus animi velit distinctio porro nulla minus voluptatum numquam dolor expedita, rem eveniet sapiente libero dolorum vero perspiciatis repellendus praesentium eius consequatur consectetur fugit recusandae corporis accusamus. Ipsum minus explicabo labore tenetur voluptatum tempore molestiae consequatur illo accusamus corporis nisi animi fugit quidem earum totam, odio harum esse magnam. Quaerat a possimus, voluptatibus explicabo ratione, molestias mollitia harum ab voluptate odit aliquid nostrum dicta facere, et libero temporibus tempora. Blanditiis maiores doloribus sed omnis harum! Eaque ipsum minima nam eum mollitia dolorem voluptatibus velit praesentium corporis pariatur! Eum eveniet doloribus, quos quod et officiis expedita aspernatur vitae reiciendis, delectus totam hic fugiat neque autem exercitationem cupiditate deleniti! Aperiam vitae quibusdam optio enim velit animi dolorum, libero sapiente explicabo dignissimos! Ut natus adipisci omnis ex itaque quo pariatur reprehenderit enim a quasi. Dignissimos assumenda laudantium natus possimus perspiciatis odit vitae, ea sequi ab voluptatibus fuga rem distinctio officiis ipsum iusto quas labore. Non itaque illo perspiciatis temporibus quis cumque. Porro adipisci, et qui ipsam modi sunt pariatur numquam harum dolorem minima, alias reiciendis explicabo quos odit repudiandae magnam tenetur atque vitae. Non soluta quisquam error neque, et maiores culpa inventore!</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos nesciunt error esse et perferendis natus quisquam obcaecati eius, adipisci cum totam vitae. Sapiente dolore voluptates aliquid id dolorum dignissimos quis. Et eius saepe officiis aut quam ratione delectus tempora doloremque.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni animi quis, ad odio ut corporis? Eius ad minima explicabo nisi vitae cupiditate asperiores molestias beatae dolore architecto veritatis reprehenderit ab iste voluptatibus, suscipit minus velit totam recusandae. Iure, maxime culpa distinctio aspernatur est sed, tempora accusantium dicta debitis deleniti quos. Necessitatibus vel sequi odio nulla ullam recusandae totam inventore, vero ea. Esse dolore molestias rem voluptatibus facere quaerat? Omnis, laboriosam adipisci! Alias veritatis quibusdam dolores laudantium corporis harum, fugit similique maiores a architecto officia reprehenderit omnis, optio ad magnam ducimus voluptatibus est qui exercitationem nemo culpa, fugiat nulla tenetur?</p>
    </RulesAndLawLayout>
  );
}